docker-php-ext-install bcmath
docker-php-ext-install ctype
docker-php-ext-install curl
docker-php-ext-install dom
docker-php-ext-install fileinfo
docker-php-ext-install json
docker-php-ext-install mbstring
docker-php-ext-install openssl
docker-php-ext-install pcre
docker-php-ext-install pdo
docker-php-ext-install pdo_mysql
docker-php-ext-install mysqli
docker-php-ext-install xml